1.


In [ ]:
import numpy as np

In [ ]:
emp = np.empty(5)
ful = np.full(5,2)
emp,ful


(array([1.e-323, 1.e-323, 1.e-323, 1.e-323, 1.e-323]), array([2, 2, 2, 2, 2]))

In [ ]:
zer = np.zeros(5)
zer

array([0., 0., 0., 0., 0.])

In [ ]:
one = np.ones(5)
one

array([1., 1., 1., 1., 1.])

In [ ]:
one_dim = np.array([1,2,3])
two_dim = np.array([[4,5,6], [7,8,9]])
combined_array = np.concatenate((np.expand_dims(one_dim, axis=0), two_dim), axis=0)
combined_array

NameError: ignored

In [ ]:
rng = np.random.default_rng(seed = 123)
arr = rng.normal(0,1,100).round(1) -  rng.normal(0,1,100).round(1)
arr
sum = 0
for i in arr:
  if i != 0:
    sum +=1
sum

97

2.

In [ ]:
mat = rng.standard_normal(30).reshape(5,-1)
arr = mat.flatten()
l = []
for i in range(len(arr)):
  sum = 0
  for j in range(i,len(arr)):
    if arr[i] >= arr[j]:
      sum +=1
  if sum == len(arr) - (i):
     print(arr[i])
     break

2.0276390593976137


In [ ]:
matrix = np.array(mat)
print('number_of_row : '  , matrix.shape[0]), print('number_of_col : ',matrix.shape[1] )

number_of_row :  5
number_of_col :  6


(None, None)

In [ ]:
mat1 = rng.standard_normal(20).reshape(5,-1)
mat2 = rng.uniform(0,1,20).reshape(5,-1)
print('Adding two matrices : ', mat1+mat2), print('Substracting two matrices : ', mat1-mat2)

Adding two matrices :  [[-0.14394454  0.18713674  1.4830047   1.20024526]
 [ 0.68903722  1.96066658  0.61962463  0.94089708]
 [ 1.19306262  0.41454453 -0.46543289  2.34062967]
 [ 1.30277721 -0.90318196 -0.96088448 -1.02846965]
 [-1.0588422   1.16405049  2.20935962  0.77202684]]
Substracting two matrices :  [[-0.36243451 -1.22830344  0.43781132 -0.01109568]
 [-0.31460562  0.3411849  -0.55016931 -0.66352862]
 [-0.1224562  -0.95536182 -1.93859415  1.1842545 ]
 [ 0.5832552  -1.6957083  -1.00553662 -1.10282607]
 [-1.9884834  -0.43989594  0.7949068   0.00224783]]


(None, None)

In [ ]:
print('Matrix multiplication :', np.matmul(mat1, np.transpose(mat2)))

Matrix multiplication : [[ 0.46593546  0.49012174  0.52808069 -0.25382837  0.37288989]
 [ 0.93713115  1.15746685  1.01723842  0.52935379  1.0879718 ]
 [ 0.30639639  0.76046531  0.30052572  0.12411643 -0.13979078]
 [-1.97587765 -2.00894134 -1.61013951 -0.2372319  -1.70929598]
 [ 1.10928434  0.71774183  0.57608267 -0.35674676  0.7934998 ]]


In [ ]:
my_array = [[1, 2, 3], [4, 5, 6]]
# Add a row
new_row = [7, 8, 9]
my_array = my_array + [new_row]
# Add a column
new_column = [10, 11]
my_array = [row + [column] for row in my_array for column in [new_column[my_array.index(row)]]]


[array([-0.25318952, -0.52058335,  0.96040801,  0.59457479]),
 array([0.1872158 , 1.15092574, 0.03472766, 0.13868423]),
 array([ 0.53530321, -0.27040865, -1.20201352,  1.76244208]),
 array([ 0.9430162 , -1.29944513, -0.98321055, -1.06564786]),
 array([-1.5236628 ,  0.36207728,  1.50213321,  0.38713734]),
 [1, 2, 3, 4, 5, 6]]

In [ ]:
mat3 = rng.standard_normal(36).reshape(6,-1)
eig = np.linalg.eig(mat3)
eig

(array([ 0.76924405+2.56050752j,  0.76924405-2.56050752j,
        -0.50993427+1.26873789j, -0.50993427-1.26873789j,
        -0.93279919+0.j        ,  0.28188614+0.j        ]),
 array([[-0.29802706+0.34621049j, -0.29802706-0.34621049j,
         -0.1618531 +0.41157817j, -0.1618531 -0.41157817j,
          0.46742881+0.j        ,  0.41202303+0.j        ],
        [ 0.12676488+0.49597469j,  0.12676488-0.49597469j,
          0.14467878+0.15997753j,  0.14467878-0.15997753j,
         -0.42932741+0.j        , -0.47967606+0.j        ],
        [ 0.13761843+0.09587995j,  0.13761843-0.09587995j,
          0.26126213-0.00854041j,  0.26126213+0.00854041j,
          0.25124085+0.j        ,  0.29779451+0.j        ],
        [-0.4333574 -0.03293752j, -0.4333574 +0.03293752j,
         -0.52617025+0.j        , -0.52617025-0.j        ,
          0.41955624+0.j        ,  0.69951854+0.j        ],
        [ 0.02393338+0.17883478j,  0.02393338-0.17883478j,
          0.44463828-0.15752501j,  0.44463828+0.15752

In [ ]:
arr2 = np.array([1,2,3,2,1,4,5,3,2,1])
frq = {}

for i in arr2:
  if i in frq:
    frq[i] += 1
  else:
    frq[i] = 1
frq

{1: 3, 2: 3, 3: 2, 4: 1, 5: 1}

In [ ]:
inver = np.linalg.inv(mat3)
inver

array([[-0.22541853,  0.10794612, -0.47813564,  0.75157806, -0.5514673 ,
         0.10367537],
       [ 0.3954277 ,  0.33863852, -0.90280366,  1.84661469, -0.77351477,
         0.38327456],
       [-0.04538164,  0.55872607, -1.12048751,  0.50035316, -0.62557546,
         0.38969106],
       [ 0.20693477,  0.10411849,  0.07739711, -0.20625745,  0.13593154,
        -0.50410477],
       [ 0.01927898,  0.05539166, -0.16043493,  0.64260525, -0.55634685,
         0.35712427],
       [ 0.17788255, -0.45334949,  0.10619693,  0.14386306,  0.09449067,
        -0.21872264]])

In [ ]:
det = np.linalg.det(mat3)
det

-22.60462811644553

In [ ]:
cor_matrix = np.corrcoef(mat3, rowvar=False)
print(cor_matrix)

[[ 1.          0.45551255 -0.37198246 -0.14614977 -0.10164007 -0.61892567]
 [ 0.45551255  1.          0.12855719  0.55287895 -0.09100678 -0.13729645]
 [-0.37198246  0.12855719  1.         -0.31243699 -0.75602742  0.55580081]
 [-0.14614977  0.55287895 -0.31243699  1.          0.64753831  0.06795382]
 [-0.10164007 -0.09100678 -0.75602742  0.64753831  1.         -0.00851694]
 [-0.61892567 -0.13729645  0.55580081  0.06795382 -0.00851694  1.        ]]


3.

In [ ]:
arr5 = np.array([1,2,3,4,3,2,1,3,2,5,6,3,2])
k = 10
condition = 3
for i in range(len(arr5)):
  if arr5[i] > condition:
    arr5[i] = k
arr5


array([ 1,  2,  3, 10,  3,  2,  1,  3,  2, 10, 10,  3,  2])

In [ ]:
for i in arr5:
  if i <= condition:
    print(i)


1
2
3
3
2
1
3
2
3
2


In [ ]:
arr
for i in range(len(arr)):
  if arr[i] < 0:
    arr[i] = 0
print(arr)

[0.  0.  1.6 1.6 1.2 0.2 0.  0.  0.  0.  0.  0.2 1.6 2.  1.6 0.  2.3 0.
 0.  0.  0.  1.1 0.7 0.8 1.1 0.  1.2 0.8 0.  0.3 0.1 0.  1.9 0.  0.  0.1
 0.2 0.6 0.  0.  1.1 0.  1.3 0.4 0.  0.  0.  0.  1.9 0.  0.  0.6 1.  0.
 0.4 0.  0.  0.  0.  0.9 1.4 0.  0.5 0.  0.  0.6 0.2 0.  1.8 0.  0.  1.1
 0.6 1.9 0.7 0.  0.  0.  0.3 0.  0.  0.7 1.4 0.6 1.1 0.5 0.  0.  0.7 0.
 0.7 0.  0.  0.8 1.2 0.  0.  0.  0.3 2.6]


In [ ]:
arr6 = np.array([[1, 2, np.nan],
                  [4, np.nan, 6],
                  [np.nan, 8, 9]])

col_mn = np.nanmean(arr6, axis=0)

nan_mask = np.isnan(arr6)
arr6[nan_mask] = col_mn
arr6

array([[1. , 2. , 2.5],
       [4. , 5. , 6. ],
       [7.5, 8. , 9. ]])

In [ ]:
position = 5
arr[position]

0.19999999999999996

In [ ]:
arr7 = np.array([1,2,3,4,0,5,4,0,6,0])
for i in range(len(arr7)):
  if arr7[i] == 0:
    print(i)

4
7
9


In [ ]:
arr8 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
k = 1

print('k+1 th row : ' , arr8[[k]])

k+1 th row :  [[4 5 6]]


In [ ]:
arr6 = np.array([[1, 2, np.nan],
                  [4, np.nan, 6],
                  [np.nan, 8, 9]])

non_numeric_col = np.isnan(arr6).any(axis=0)
numeric_array = arr6[:, ~non_numeric_col]

print(numeric_array)


[]


In [ ]:
arr8
x = 4
row_numbers = np.where(np.any(arr8 > x, axis=1))[0]
print(row_numbers)


[1 2]


4.

In [ ]:
arr9 = np.array([9, 2, 7, 4, 1, 5, 8, 3, 6])
sorted_indices = np.argsort(arr9)
print(sorted_indices)

[4 1 7 3 5 8 2 6 0]


In [ ]:
k = 4
smallest_values = np.partition(arr9, k)[:k]
print(smallest_values)

[1 2 3 4]


In [ ]:
n = 3
largest_values = np.partition(arr9, -n)[-n:]
print(largest_values)

[7 8 9]


In [ ]:
sorted_values = np.sort(arr9)
sorted_values

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
non_integer_values = arr[~np.isin(arr, arr.astype(int))]

print(non_integer_values)


[1.6 1.6 1.2 0.2 0.2 1.6 1.6 2.3 1.1 0.7 0.8 1.1 1.2 0.8 0.3 0.1 1.9 0.1
 0.2 0.6 1.1 1.3 0.4 1.9 0.6 0.4 0.9 1.4 0.5 0.6 0.2 1.8 1.1 0.6 1.9 0.7
 0.3 0.7 1.4 0.6 1.1 0.5 0.7 0.7 0.8 1.2 0.3 2.6]


In [ ]:
sorted_indices = np.argsort(arr)
print(sorted_indices)

[ 0 39 41 44 45 46 47 50 53 55 56 57 58 61 63 64 67 69 97 96 95 92 91 89
 38 87 80 79 77 76 75 70 86 34 49  1  6  7  8 31  9 10 15 33 28 17 18 19
 20 25 30 35  5 11 66 36 29 78 98 43 54 62 85 65 72 51 83 37 88 90 74 22
 81 93 23 27 59 52 24 21 71 84 40 94  4 26 42 60 82  3 12 14  2 68 73 48
 32 13 16 99]


5.

In [ ]:
rngg = np.random.default_rng(seed =123)
rn_arr = rngg.uniform(0,1,10)
rn_arr

array([0.68235186, 0.05382102, 0.22035987, 0.18437181, 0.1759059 ,
       0.81209451, 0.923345  , 0.2765744 , 0.81975456, 0.88989269])

In [ ]:
rn_mat = rngg.uniform(0,1,20).reshape(5,-1)
rn_mat

array([[0.51297046, 0.2449646 , 0.8242416 , 0.21376296],
       [0.74146705, 0.6299402 , 0.92740726, 0.23190819],
       [0.79912513, 0.51816504, 0.23155562, 0.16590399],
       [0.49778897, 0.58272464, 0.18433799, 0.01489492],
       [0.47113323, 0.72824333, 0.91860049, 0.62553401]])

In [ ]:
rn_mat1 = rngg.normal(0,1,20).reshape(5,-1)
rn_mat1

array([[-0.36176687, -1.2302322 ,  1.22622929, -2.17204389],
       [-0.37014735,  0.16438007,  0.85988118,  1.76166124],
       [ 0.99332378, -0.29152143,  0.72812756, -1.26160032],
       [ 1.42993853, -0.15647532, -0.67375915, -0.6390601 ],
       [-0.06136133, -0.39278492,  2.28990995, -0.71818115]])

6.

In [ ]:
import pandas as pd

In [ ]:
dat = [[1, 2, 3],
        [4, 5, 6]]
df = pd.DataFrame(dat)

In [ ]:
dat2 = {'C1': [1, 2, 3],
        'C2': np.array([4, 5, 6]),
        'C3': [7.0, 8.0, 9.0]}

df2 = pd.DataFrame(dat2)

In [ ]:
lst_of_lst = [[1, 2, 3],
        [4, 5, 6]]
df = pd.DataFrame(lst_of_lst)

In [ ]:
tup = [(1, 2, 3),
        (4, 5, 6),
        (7, 8, 9)]
df = pd.DataFrame(tup)

In [ ]:
dat3 = [
    {'C1': 1, 'C2': 'A', 'C3': True},
    {'C1': 2, 'C2': 'B', 'C3': False},
    {'C1': 3, 'C2': 'C', 'C3': True}
]

df3 = pd.DataFrame(dat3)

In [ ]:
series1 = pd.Series([1, 2, 3])
series2 = pd.Series(['A', 'B', 'C'])
series3 = pd.Series([True, False, True])
df = pd.concat([series1, series2, series3], axis=1)
df3 = pd.DataFrame(df)


In [ ]:
new_index = ['Z', 'Y', 'X', 'W']
reindexed_df = df3.reindex(new_index)

In [ ]:
reset_df = reindexed_df.reset_index()

In [ ]:
dat4 = {'A': [1, 2, 3],
        'B': [4, 5, 6],
        'C': [7, 8, 9]}

df4 = pd.DataFrame(dat4, index=['X', 'Y', 'Z'])
df4 = df4.rename(columns={'A': 'Column1', 'B': 'Column2', 'C': 'Column3'})
df4 = df4.rename(index={'X': 'Row1', 'Y': 'Row2', 'Z': 'Row3'})

7.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = {'Name': ['John', 'Jane', 'Mike'],
        'Age': [25, 30, 35],
        'City': ['New York', 'London', 'Paris']}
df = pd.DataFrame(data)
for i in range(len(df)):
    name = df.loc[i, 'Name']
    age = df.loc[i, 'Age']
    city = df.loc[i, 'City']
    print(name,age,city)


John 25 New York
Jane 30 London
Mike 35 Paris


In [ ]:
for index, row in df.iterrows():
    name = row['Name']
    age = row['Age']
    city = row['City']
    print(name, age, city)


John 25 New York
Jane 30 London
Mike 35 Paris


In [ ]:
condition = df['Age'] > 30
filtered_df = df[condition]

In [ ]:
#kth row
k = 2
df.iloc[k], df.iat[2,1]


(Name     Mike
 Age        35
 City    Paris
 Name: 2, dtype: object,
 35)

In [ ]:
df['Name'][0:3]

0    John
1    Jane
2    Mike
Name: Name, dtype: object

In [ ]:
condition = df['Age'] > 30
df.drop(df[condition].index)

Name  Age      City
0  John   25  New York
1  Jane   30    London

In [ ]:
new_row = {'Name': 'Emily', 'Age': 28, 'City': 'Sydney'}
df = df.append(new_row, ignore_index=True)
df

<ipython-input-22-0938a9ef1b80>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)


Name  Age      City
0   John   25  New York
1   Jane   30    London
2   Mike   35     Paris
3  Emily   28    Sydney

In [ ]:
rows_list = df.values.tolist()
rows_list

[['John', 25, 'New York'],
 ['Jane', 30, 'London'],
 ['Mike', 35, 'Paris'],
 ['Emily', 28, 'Sydney']]

In [ ]:
# Rank rows based on the 'Age' column
df['Rank'] = df['Age'].rank(method='min')
print(df)

   Name  Age      City  Rank
0  John   25  New York   1.0
1  Jane   30    London   2.0
2  Mike   35     Paris   3.0


In [ ]:
# Sort rows based on the 'Age' column
sorted_df = df.sort_values('Age')
print(sorted_df)

   Name  Age      City  Rank
0  John   25  New York   1.0
1  Jane   30    London   2.0
2  Mike   35     Paris   3.0


In [ ]:
# Select rows with the maximum and minimum 'Age' values
max_age_row = df.loc[df['Age'].idxmax()]
min_age_row = df.loc[df['Age'].idxmin()]
max_age_row, min_age_row

(Name     Mike
 Age        35
 City    Paris
 Rank      3.0
 Name: 2, dtype: object,
 Name        John
 Age           25
 City    New York
 Rank         1.0
 Name: 0, dtype: object)

In [ ]:
substring = 'M'
filtered_df = df[df['Name'].str.contains(substring)]
filtered_df

Name  Age   City  Rank
2  Mike   35  Paris   3.0

In [ ]:
df.set_index('Name', inplace = True)

In [ ]:
random_rows = df.sample(n=2)
random_rows

Age    City
Name             
Mike   35   Paris
Jane   30  London

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame()
values = [1, 2, 3, 4, 5]
for i in range(len(values)):
    column_name = f'Column{i+1}'
    df[column_name] = values[i]
print(df)

In [ ]:
#col_names
df.columns

In [ ]:
#rename
df = df.rename(columns = {'Column1': 'A'})
df.columns

In [ ]:
import seaborn as sns
penguin = sns.load_dataset('penguins')

In [ ]:
#unique values
uniq_island = penguin['island'].unique()
uniq_island

In [ ]:
#index numbeer
bill_depth = penguin['bill_depth_mm']
for i in range(len(bill_depth)):
  if bill_depth[i] == 18:
    print(i)

In [ ]:
#new_column
df = pd.DataFrame({'A': [1, 2, 3, 4, 5]})

df['B'] = df['A'] * 2

In [ ]:
df['C'] = [0 if x > 3 else 1 for x in df['A']]

In [ ]:
#frequency
penguin['island'].value_counts()

In [ ]:
#split
df = pd.DataFrame({'Text': ['Hello World', 'OpenAI Model', 'Data Science']})

df[['Column1', 'Column2']] = df['Text'].str.split(' ', 1, expand=True)

print(df)

In [ ]:
#index numbeer of min and max

for i in range(len(bill_depth)):
  if bill_depth[i] == bill_depth.min():
    print(i)

In [ ]:
for i in range(len(bill_depth)):
  if bill_depth[i] == bill_depth.max():
    print(i)

In [ ]:
penguin['bill_depth_mm'] - penguin['bill_length_mm']

In [ ]:
#drop columns
df.drop[['Column1', 'Column2']]

In [ ]:
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

df = pd.DataFrame(my_array)

In [ ]:
dict = {
    'Name': ['John', 'Emma', 'Peter', 'Olivia'],
    'Age': [25, 28, 30, 27],
    'City': ['New York', 'London', 'Paris', 'Sydney']
}
df = pd.DataFrame(dict)

In [ ]:
names = ['John', 'Emma', 'Peter', 'Olivia']
ages = [25, 28, 30, 27]
cities = ['New York', 'London', 'Paris', 'Sydney']
df = pd.DataFrame({'Name': names, 'Age': ages, 'City': cities})

In [ ]:
import numpy as np
data = np.random.rand(3, 3)

column_names = ['Column1', 'Column2', 'Column3']
df = pd.DataFrame(data, columns=column_names)
df

In [ ]:
#access element
df['Column1'][0]

In [ ]:
#data time format
df = pd.DataFrame({'Date': ['2022-01-01', '2022-02-01', '2022-03-01']})
df['Date'] = pd.to_datetime(df['Date'])
df